language: node_js
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb

env:
  global:
    - GH_REF: github.com/vzellweg/beattweak.git
    - GH_OWNER: vzellweg
    - GH_PROJECT_NAME: beattweak

install:
  # Check the size of
  - caches -sh ./node_modules ./test/tmp/deps/node_modules || true
  - npm install -g npm@latest
  # Instal npm dependecies and ensure that npm cache is not stale
  - rm -rf node_modules 
  - npm install

after_success:
  - npm build
